name: Build packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.10'

    - name: Install PupNet
      run: dotnet tool update -g KuiperZone.PupNet
      
    - name: Verify PupNet installation
      run: pupnet --version